name: 🐛 Bug Report
description: Signaler un bug pour nous aider à améliorer FinOps
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler un bug !

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du problème
      placeholder: Quand je fais X, Y arrive au lieu de Z...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Étapes pour reproduire le comportement
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Ce qui aurait dû se passer
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      options:
        - Local (Docker)
        - Railway
        - Fly.io
        - AWS/GCP
        - Autre
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version de FinOps
      placeholder: ex: 1.0.0

  - type: textarea
    id: logs
    attributes:
      label: Logs d'erreur
      description: Copier-coller les logs pertinents
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: J'accepte de suivre le Code of Conduct de FinOps
          required: true
